local roman_numerals = require('roman-numerals')

describe('roman-numerals', function()
    [$roman_numerals.to_roman~ "1 is i" ["1"] "I"]
    [$roman_numerals.to_roman~ "2 is ii" ["2"] "II"]
    [$roman_numerals.to_roman~ "3 is iii" ["3"] "III"]
    [$roman_numerals.to_roman~ "4 is iv" ["4"] "IV"]
    [$roman_numerals.to_roman~ "5 is v" ["5"] "V"]
    [$roman_numerals.to_roman~ "6 is vi" ["6"] "VI"]
    [$roman_numerals.to_roman~ "9 is ix" ["9"] "IX"]
    [$roman_numerals.to_roman~ "16 is xvi" ["16"] "XVI"]
    [$roman_numerals.to_roman~ "27 is xxvii" ["27"] "XXVII"]
    [$roman_numerals.to_roman~ "48 is xlviii" ["48"] "XLVIII"]
    [$roman_numerals.to_roman~ "49 is xlix" ["49"] "XLIX"]
    [$roman_numerals.to_roman~ "59 is lix" ["59"] "LIX"]
    [$roman_numerals.to_roman~ "66 is lxvi" ["66"] "LXVI"]
    [$roman_numerals.to_roman~ "93 is xciii" ["93"] "XCIII"]
    [$roman_numerals.to_roman~ "141 is cxli" ["141"] "CXLI"]
    [$roman_numerals.to_roman~ "163 is clxiii" ["163"] "CLXIII"]
    [$roman_numerals.to_roman~ "166 is clxvi" ["166"] "CLXVI"]
    [$roman_numerals.to_roman~ "402 is cdii" ["402"] "CDII"]
    [$roman_numerals.to_roman~ "575 is dlxxv" ["575"] "DLXXV"]
    [$roman_numerals.to_roman~ "666 is dclxvi" ["666"] "DCLXVI"]
    [$roman_numerals.to_roman~ "911 is cmxi" ["911"] "CMXI"]
    [$roman_numerals.to_roman~ "1024 is mxxiv" ["1024"] "MXXIV"]
    [$roman_numerals.to_roman~ "1666 is mdclxvi" ["1666"] "MDCLXVI"]
    [$roman_numerals.to_roman~ "3000 is mmm" ["3000"] "MMM"]
    [$roman_numerals.to_roman~ "3001 is mmmi" ["3001"] "MMMI"]
    [$roman_numerals.to_roman~ "3888 is mmmdccclxxxviii" ["3888"] "MMMDCCCLXXXVIII"]
    [$roman_numerals.to_roman~ "3999 is mmmcmxcix" ["3999"] "MMMCMXCIX"]
