use ./bob

fn tests {
  put [
    [$bob:hey~ "stating something" ["Tom-ay-to, tom-aaaah-to."] "Whatever."]
    [$bob:hey~ "shouting" ["WATCH OUT!"] "Whoa, chill out!"]
    [$bob:hey~ "shouting gibberish" ["FCECDFCAAB"] "Whoa, chill out!"]
    [$bob:hey~ "asking a question" ["Does this cryogenic chamber make me look fat?"] "Sure."]
    [$bob:hey~ "asking a numeric question" ["You are, what, like 15?"] "Sure."]
    [$bob:hey~ "asking gibberish" ["fffbbcbeab?"] "Sure."]
    [$bob:hey~ "talking forcefully" ["Hi there!"] "Whatever."]
    [$bob:hey~ "using acronyms in regular speech" ["It's OK if you don't want to go work for NASA."] "Whatever."]
    [$bob:hey~ "forceful question" ["WHAT'S GOING ON?"] "Calm down, I know what I'm doing!"]
    [$bob:hey~ "shouting numbers" ["1, 2, 3 GO!"] "Whoa, chill out!"]
    [$bob:hey~ "no letters" ["1, 2, 3"] "Whatever."]
    [$bob:hey~ "question with no letters" ["4?"] "Sure."]
    [$bob:hey~ "shouting with special characters" ["ZOMG THE %^*@#$(*^ ZOMBIES ARE COMING!!11!!1!"] "Whoa, chill out!"]
    [$bob:hey~ "shouting with no exclamation mark" ["I HATE THE DENTIST"] "Whoa, chill out!"]
    [$bob:hey~ "statement containing question mark" ["Ending with ? means a question."] "Whatever."]
    [$bob:hey~ "non-letters with question" [":) ?"] "Sure."]
    [$bob:hey~ "prattling on" ["Wait! Hang on. Are you going to be OK?"] "Sure."]
    [$bob:hey~ "silence" [""] "Fine. Be that way!"]
    [$bob:hey~ "prolonged silence" ["          "] "Fine. Be that way!"]
    [$bob:hey~ "alternate silence" ["\t\t\t\t\t\t\t\t\t\t"] "Fine. Be that way!"]
    [$bob:hey~ "starting with whitespace" ["         hmmmmmmm..."] "Whatever."]
    [$bob:hey~ "ending with whitespace" ["Okay if like my  spacebar  quite a bit?   "] "Sure."]
    [$bob:hey~ "other whitespace" ["\n\r \t"] "Fine. Be that way!"]
    [$bob:hey~ "non-question ending with whitespace" ["This is a statement ending with whitespace      "] "Whatever."]
    [$bob:hey~ "multiple line question" ["\nDoes this cryogenic chamber make\n me look fat?"] "Sure."]
  ]
}